// flow-typed signature: 133e10dc9a954a970f94b73e720655b3
// flow-typed version: <<STUB>>/jest-dom_v^2.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-dom/dist/__tests__/helpers/document' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/helpers/test-utils' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-be-disabled' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-be-empty' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-be-in-the-document' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-be-in-the-dom' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-be-visible' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-contain-element' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-contain-html' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-have-attribute' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-have-class' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-have-focus' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-have-form-values' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-have-style' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/to-have-text-content' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/__tests__/utils' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/extend-expect' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/index' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-be-disabled' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-be-empty' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-be-in-the-document' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-be-in-the-dom' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-be-visible' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-contain-element' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-contain-html' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-have-attribute' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-have-class' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-have-focus' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-have-form-values' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-have-style' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/to-have-text-content' {
  declare module.exports: any;
}

declare module 'jest-dom/dist/utils' {
  declare module.exports: any;
}

declare module 'jest-dom/extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-dom/dist/__tests__/helpers/document.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/helpers/document'>;
}
declare module 'jest-dom/dist/__tests__/helpers/test-utils.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/helpers/test-utils'>;
}
declare module 'jest-dom/dist/__tests__/to-be-disabled.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-be-disabled'>;
}
declare module 'jest-dom/dist/__tests__/to-be-empty.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-be-empty'>;
}
declare module 'jest-dom/dist/__tests__/to-be-in-the-document.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-be-in-the-document'>;
}
declare module 'jest-dom/dist/__tests__/to-be-in-the-dom.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-be-in-the-dom'>;
}
declare module 'jest-dom/dist/__tests__/to-be-visible.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-be-visible'>;
}
declare module 'jest-dom/dist/__tests__/to-contain-element.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-contain-element'>;
}
declare module 'jest-dom/dist/__tests__/to-contain-html.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-contain-html'>;
}
declare module 'jest-dom/dist/__tests__/to-have-attribute.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-have-attribute'>;
}
declare module 'jest-dom/dist/__tests__/to-have-class.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-have-class'>;
}
declare module 'jest-dom/dist/__tests__/to-have-focus.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-have-focus'>;
}
declare module 'jest-dom/dist/__tests__/to-have-form-values.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-have-form-values'>;
}
declare module 'jest-dom/dist/__tests__/to-have-style.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-have-style'>;
}
declare module 'jest-dom/dist/__tests__/to-have-text-content.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/to-have-text-content'>;
}
declare module 'jest-dom/dist/__tests__/utils.js' {
  declare module.exports: $Exports<'jest-dom/dist/__tests__/utils'>;
}
declare module 'jest-dom/dist/extend-expect.js' {
  declare module.exports: $Exports<'jest-dom/dist/extend-expect'>;
}
declare module 'jest-dom/dist/index.js' {
  declare module.exports: $Exports<'jest-dom/dist/index'>;
}
declare module 'jest-dom/dist/to-be-disabled.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-be-disabled'>;
}
declare module 'jest-dom/dist/to-be-empty.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-be-empty'>;
}
declare module 'jest-dom/dist/to-be-in-the-document.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-be-in-the-document'>;
}
declare module 'jest-dom/dist/to-be-in-the-dom.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-be-in-the-dom'>;
}
declare module 'jest-dom/dist/to-be-visible.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-be-visible'>;
}
declare module 'jest-dom/dist/to-contain-element.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-contain-element'>;
}
declare module 'jest-dom/dist/to-contain-html.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-contain-html'>;
}
declare module 'jest-dom/dist/to-have-attribute.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-have-attribute'>;
}
declare module 'jest-dom/dist/to-have-class.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-have-class'>;
}
declare module 'jest-dom/dist/to-have-focus.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-have-focus'>;
}
declare module 'jest-dom/dist/to-have-form-values.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-have-form-values'>;
}
declare module 'jest-dom/dist/to-have-style.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-have-style'>;
}
declare module 'jest-dom/dist/to-have-text-content.js' {
  declare module.exports: $Exports<'jest-dom/dist/to-have-text-content'>;
}
declare module 'jest-dom/dist/utils.js' {
  declare module.exports: $Exports<'jest-dom/dist/utils'>;
}
declare module 'jest-dom/extend-expect.js' {
  declare module.exports: $Exports<'jest-dom/extend-expect'>;
}
