// flow-typed signature: 2c3e792496c6fed08eac26bd99ce34a5
// flow-typed version: <<STUB>>/redux-vanilla_v^0.0.1-beta2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-vanilla'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-vanilla' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-vanilla/es/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/lib/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/connect' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/connect.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/index.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/Provider' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/Provider.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/testutils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-vanilla/es/index.js' {
  declare module.exports: $Exports<'redux-vanilla/es/index'>;
}
declare module 'redux-vanilla/lib/index.js' {
  declare module.exports: $Exports<'redux-vanilla/lib/index'>;
}
declare module 'redux-vanilla/src/connect.js' {
  declare module.exports: $Exports<'redux-vanilla/src/connect'>;
}
declare module 'redux-vanilla/src/connect.test.js' {
  declare module.exports: $Exports<'redux-vanilla/src/connect.test'>;
}
declare module 'redux-vanilla/src/index.js' {
  declare module.exports: $Exports<'redux-vanilla/src/index'>;
}
declare module 'redux-vanilla/src/index.test.js' {
  declare module.exports: $Exports<'redux-vanilla/src/index.test'>;
}
declare module 'redux-vanilla/src/Provider.js' {
  declare module.exports: $Exports<'redux-vanilla/src/Provider'>;
}
declare module 'redux-vanilla/src/Provider.test.js' {
  declare module.exports: $Exports<'redux-vanilla/src/Provider.test'>;
}
declare module 'redux-vanilla/src/testutils.js' {
  declare module.exports: $Exports<'redux-vanilla/src/testutils'>;
}
