version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:cov
      - run: yarn codecov
  lint:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  flow:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn flow

workflows:
  version: 2
  myworkflow:
    jobs:
      - build
      - test
      - lint
      - flow